name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker to use the gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-predictor . --platform linux/amd64
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-predictor

    - name: Deploy to Cloud Run
      id: deploy
      run: |
        echo "Deploying to Google Cloud Run..."
        URL=$(gcloud run deploy flight-predictor-api --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/flight-predictor --platform managed --region us-central1 --allow-unauthenticated --format="value(status.url)")
        echo "::set-output name=url::$URL"
        echo "Deployment completed at $URL"

    - name: Set STRESS_URL for Makefile
      run: echo "STRESS_URL=${{ steps.deploy.outputs.url }}" >> $GITHUB_ENV

    - name: Run stress tests
      run: |
        make stress-test STRESS_URL=${{ env.STRESS_URL }}